#!/bin/bash

JMETER_VERSION=${JMETER_VERSION:-"5.4.1"}
JMETER_PLUGINS_MANAGER_VERSION=${JMETER_PLUGINS_MANAGER_VERSION:-"1.3"}
CMDRUNNER_VERSION=${CMDRUNNER_VERSION:-"2.2"}

# Example build line
podman build \
    --build-arg JMETER_VERSION=${JMETER_VERSION} \
    --build-arg JMETER_PLUGINS_MANAGER_VERSION=${JMETER_PLUGINS_MANAGER_VERSION} \
    --build-arg CMDRUNNER_VERSION=${CMDRUNNER_VERSION} \
    -t "ghcr.io/cage1016/jmeter-s390x:${JMETER_VERSION}" .
